### ISSUE TITLE
DogeWallet misnamed in Wallets

### ISSUE THREAD

**Issue by nutildah** [dogecoinfoundation/dogecoin.com#288] opened 2023-04-26 13:02 UTC
On Mar 22, the name of "DogeWallet", the Dogeparty wallet released in Oct 2021, was changed to "XDP Wallet". This has never been the wallet's actual name. I understand there may potentially be some confusion as the wallet was initially titled "Doge Wallet" on dogecoin.com, when the actual name of the wallet is "DogeWallet" (without the space). This is the only Dogecoin wallet client with active development that has this name and its GitHub shows up as the first result in a Google search for the term.

To allay any potential confusion with "Dogecoin Core" (if this was the reason the name was changed in the first place), perhaps additional clarification could be made by titling the wallet "DogeWallet (Dogeparty)". But leaving the name as "XDP Wallet" doesn't make sense as its never been called that and it is confusing for people looking for the DogeWallet.

Here is the pull request for the name change, which was committed on Mar 22:

https://github.com/dogecoinfoundation/dogecoin.com/pull/270

Thank you for your attention to this matter.

![image](https://user-images.githubusercontent.com/7720163/233828107-98c1ecfd-96f3-4590-a4e7-faf5c169cb3f.png)
![image](https://user-images.githubusercontent.com/7720163/233828123-5601452a-848d-4361-b165-fe30009a5809.png)

**Comment by michilumin** [comment] 2023-04-26 20:05
I propose changing the name to 'dogewallet' as requested but adding an interim gate/catch that downloaders must read, explaining what 'dogewallet' actually is, and that it is not endorsed by or the 'official' application of dogecoin. (Not even Dogecoin Core does this.)  - as there is community history in people feeling that the name 'dogewallet' inferred primacy / officiality and de-facto endorsement. 

If the issue truly is about the "name being changed" this alleviates that concern; there is nothing saying that the dogecoin.com site cannot disavow endorsement and indicate the software roots/origin.

**Comment by nutildah** [comment] 2023-04-27 05:44
> I propose changing the name to 'dogewallet' as requested but adding an interim gate/catch that downloaders must read, explaining what 'dogewallet' actually is, and that it is not endorsed by or the 'official' application of dogecoin. (Not even Dogecoin Core does this.) - as there is community history in people feeling that the name 'dogewallet' inferred primacy / officiality and de-facto endorsement.

I'm not entirely certain what you mean by "gate/catch" but if you feel adding something beyond "DogeWallet (Dogeparty wallet)" is necessary then that is OK with me.

> If the issue truly is about the "name being changed" this alleviates that concern; there is nothing saying that the dogecoin.com site cannot disavow endorsement and indicate the software's roots/origin.

The issue stems from the title of the DogeWallet being changed to an incorrect name. It's akin to operating a directory of fast food places and changing the listing for "Burger King" to "Home of the Whopper".

If you feel additional descriptors are required to ensure "primacy/officiality" or endorsement is not inferred, that is fine. From my personal point of view adding "(Dogeparty wallet)" should suffice in terms of resolving potential confusion.

**Comment by nutildah** [comment] 2023-07-08 03:22
Hello, we're coming up on 2.5 months since this issue was raised. It looked like we were in agreement on a solution in April. Can you please change the name of the wallet to "DogeWallet (Dogeparty wallet)"? As a reminder, it has never been referred to as "XDP Wallet". This is an incorrect name. Thank you for your attention to this matter.

**Comment by cojohen** [comment] 2023-07-15 17:54
@nutildah Kindly close this issue please. The changes have been merged and the issue is corrected on the website.

**Comment by qlpqlp** [comment] 2024-06-20 13:30
This issue was already resolved.

**Closed by qlpqlp** 2024-06-20 13:30 UTC
